name: build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo apt-get install fonts-nanum fonts-noto-cjk
        pip3 install markdown
    
    - name: Make resume
      run: python3 resume.py --debug
    
    - name: Rename output
      run: mv resume.pdf resume_ubuntu.pdf
    
    - name: Commit and push PDF
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add resume_ubuntu.pdf
        git commit -m "Update resume PDF"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive resume.pdf
      uses: actions/upload-artifact@v4
      with:
        path: "*.pdf"
