name: build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install markdown
    
    - name: Make resume
      run: python3 resume.py --debug
      
    - name: Rename output
      run: |
        mv resume.pdf resume_ubuntu.pdf
        mv resume.html resume_ubuntu.html
    
    - name: Archive resume.html and resume.pdf
      uses: actions/upload-artifact@v4
      with:
        path: |
          *.pdf
          *.html
